name: white_label
description: "White label app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.3.3
  icons_launcher: ^3.0.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/qwe/images/icon.png
    - assets/asd/images/icon.png
    - assets/zxc/images/icon.png